import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN">
      <body className="antialiased text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900 transition-colors">
        {children}
      </body>
    </html>
  )
}
