import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './(root)/globals.css'
import Header from './(root)/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN" className="dark">
      <body
        className={`antialiased text-slate-900 dark:text-slate-50 bg-white dark:bg-slate-950 transition-colors ${inter.className}`}
      >
        <div className="relative max-w-5xl mx-auto bg-inherit">
          <Header />

          <main className="relative px-4 pt-32 pb-4 sm:pb-8">{children}</main>
        </div>

        <script src="/iconfont.js" async></script>
      </body>
    </html>
  )
}
